use anyhow::Result;
use std::{fs, path::Path};

use crate::{emit_errors, fail};

pub(crate) fn verify_plugin_marketplace_gate(root: &Path) -> Result<()> {
    let mut errors = Vec::new();
    let monorepo_root = root.parent().unwrap_or_else(|| Path::new(".."));
    let plugin_root = monorepo_root.join("flare-sdk-plugin");
    let sdk_root = monorepo_root.join("flare-im-core-sdk");

    require_contains_all(
        &mut errors,
        &root.join("docs/plugin-marketplace.md"),
        "plugin marketplace doc",
        &[
            "composition-time",
            "runtimeInstall",
            "manifestSha256",
            "manifest SHA-256 integrity",
            "cargo xtask plugin-verify",
            "client.capabilities.dispatchCapability",
        ],
    );

    require_contains_all(
        &mut errors,
        &plugin_root.join("catalog/plugins.json"),
        "plugin catalog",
        &[
            "\"schema\": \"flare.im.sdk.plugin.catalog.v1\"",
            "\"id\": \"sdk.plugin.av\"",
            "\"id\": \"sdk.plugin.ai\"",
            "\"distribution\": \"composition-time\"",
            "\"runtimeInstall\": \"not-supported\"",
            "\"manifestSha256\"",
            "\"manifestPath\": \"flare-sdk-plugin-call/plugin.json\"",
            "\"manifestPath\": \"flare-sdk-plugin-ai/plugin.json\"",
        ],
    );
    require_contains_all(
        &mut errors,
        &plugin_root.join("schema/plugin_manifest.schema.json"),
        "plugin manifest schema",
        &[
            "\"title\": \"SdkPluginManifest\"",
            "\"operations\"",
            "\"permissions\"",
            "\"uiKits\"",
            "\"namespaces\"",
        ],
    );
    require_contains_all(
        &mut errors,
        &plugin_root.join("flare-sdk-plugin-ai/plugin.json"),
        "ai plugin manifest",
        &[
            "\"id\": \"sdk.plugin.ai\"",
            "\"namespaces\": [\"ai\"]",
            "\"ai.local_model\"",
            "\"ai.message_context\"",
            "\"search.semantic\"",
            "\"message.translate\"",
            "\"reply.suggest\"",
            "\"inputSchema\"",
            "\"outputSchema\"",
            "\"query\"",
            "\"target_locale\"",
            "\"recent_message_ids\"",
            "\"ai.model.ready\"",
            "\"ai.model.unavailable\"",
            "\"model_id\"",
            "\"capabilities\"",
            "\"semantic_search\"",
            "\"retryable\"",
        ],
    );

    require_contains_all(
        &mut errors,
        &plugin_root.join("flare-sdk-plugin-call/plugin.json"),
        "call plugin manifest",
        &[
            "\"id\": \"sdk.plugin.av\"",
            "\"namespaces\": [\"rtc\"]",
            "\"platforms\"",
            "\"operations\"",
        ],
    );

    for generated in [
        "generated/sdk_plugin_ai/typescript/pluginApi.ts",
        "generated/sdk_plugin_ai/flutter/sdk_plugin_ai_plugin_api.dart",
        "generated/sdk_plugin_ai/android/SdkPluginAiPluginApi.kt",
        "generated/sdk_plugin_ai/ios/SdkPluginAiPluginApi.swift",
        "generated/sdk_plugin_ai/harmonyos-arkts/SdkPluginAiPluginApi.ets",
        "generated/sdk_plugin_ai/cangjie/SdkPluginAiPluginApi.cj",
        "generated/sdk_plugin_av/typescript/pluginApi.ts",
        "generated/sdk_plugin_av/flutter/sdk_plugin_av_plugin_api.dart",
        "generated/sdk_plugin_av/android/SdkPluginAvPluginApi.kt",
        "generated/sdk_plugin_av/ios/SdkPluginAvPluginApi.swift",
        "generated/sdk_plugin_av/harmonyos-arkts/SdkPluginAvPluginApi.ets",
        "generated/sdk_plugin_av/cangjie/SdkPluginAvPluginApi.cj",
    ] {
        require_contains_all(
            &mut errors,
            &plugin_root.join(generated),
            "generated plugin API stub",
            &[
                "GENERATED by `cargo xtask plugin-codegen`",
                "dispatchCapability",
            ],
        );
    }

    require_contains_all(
        &mut errors,
        &sdk_root.join("src/extension/capability/registry.rs"),
        "SDK capability registry",
        &[
            "pub fn register",
            "pub fn disable",
            "pub fn list_manifests",
            "pub async fn invoke",
            "ensure_plugin_can_invoke",
            "manifest_operations_gate_dispatch",
        ],
    );
    require_contains_all(
        &mut errors,
        &sdk_root.join("xtask/src/plugin_codegen.rs"),
        "plugin codegen gate",
        &[
            "verify_catalog",
            "schema_for!(SdkPluginManifest)",
            "write_stubs",
            "duplicate plugin catalog id",
            "distribution must be composition-time",
            "runtimeInstall must be not-supported",
            "manifestSha256",
            "sha256_file",
            "sourcePath",
            "sourcePath {} must match manifest directory",
            "category {} must match manifest namespace",
            "namespace",
        ],
    );
    require_contains_all(
        &mut errors,
        &sdk_root.join("src/extension/capability/manifest.rs"),
        "plugin manifest typed event validator",
        &[
            "pub struct SdkPluginEventManifest",
            "pub schema: Value",
            "pub struct SdkPluginPermissionManifest",
            "pub description: String",
            "#[schemars(length(min = 1))]",
            "duplicate_event",
            "event_schema_required",
            "permission_description_required",
        ],
    );

    emit_errors("plugin marketplace gate", errors)
}

fn require_contains_all(errors: &mut Vec<String>, path: &Path, label: &str, needles: &[&str]) {
    let Ok(text) = fs::read_to_string(path) else {
        fail(
            errors,
            format!("{label} missing or unreadable: {}", path.display()),
        );
        return;
    };

    for needle in needles {
        if !text.contains(needle) {
            fail(
                errors,
                format!("{label} missing `{needle}` in {}", path.display()),
            );
        }
    }
}
