[package]
name = "flare-im-core-sdk-storage-sqlite"
version = "0.2.0"
edition = "2024"
rust-version = "1.94.0"
authors = ["Flare Team"]
license = "MIT"
description = "Flare IM Core SDK - SQLite 连接与运行时（pool + schema 注册"

[dependencies]
anyhow = { workspace = true }
log = "0.4"
once_cell = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
