include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
    - always_use_package_imports
    - avoid_relative_lib_imports
    - directives_ordering
    - sort_pubspec_dependencies
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - prefer_single_quotes

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore
