#!/usr/bin/env python3
"""Generate client init/config contract artifacts from contract/client_config.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACT_DIR = ROOT / "contract"
CLIENT_CONFIG_JSON = CONTRACT_DIR / "client_config.json"
RUNTIME_OUT = ROOT / "runtime" / "src" / "generated" / "client_config.rs"
WASM_OUT = ROOT / "wasm" / "src" / "generated" / "client_config.rs"
UNIFFI_OUT = ROOT / "uniffi" / "src" / "generated" / "client_config.rs"
C_OUT = ROOT / "c" / "src" / "generated" / "client_config.rs"


def load_doc() -> dict:
    with CLIENT_CONFIG_JSON.open("r", encoding="utf-8") as file:
        return json.load(file)


def render_runtime(doc: dict) -> str:
    example = json.dumps(
        doc.get("initRequest", {}).get("example", {}),
        ensure_ascii=False,
        indent=2,
    )
    schema = json.dumps(doc, ensure_ascii=False)
    return f"""// @generated by bindings/contract/tools/client_config_codegen.py
// Source: bindings/contract/client_config.json

/// Full client config contract document (JSON).
pub const CLIENT_CONFIG_CONTRACT_JSON: &str = r#"{schema}"#;

/// Example `client.init` / `sdk.init` request body.
pub const CLIENT_INIT_REQUEST_EXAMPLE_JSON: &str = r#"{example}"#;
"""


def render_wasm(_doc: dict) -> str:
    return """// @generated by bindings/contract/tools/client_config_codegen.py
// Source: bindings/contract/client_config.json

use wasm_bindgen::prelude::*;

/// Example init JSON for Web hosts (same shape as C/Tauri `sdk_config`).
#[wasm_bindgen(js_name = flareClientInitExampleJson)]
pub fn flare_client_init_example_json() -> String {
    flare_im_core_sdk_bindings_runtime::CLIENT_INIT_REQUEST_EXAMPLE_JSON.to_string()
}

/// Full client config contract (transport policy, race order, URLs).
#[wasm_bindgen(js_name = flareClientConfigContractJson)]
pub fn flare_client_config_contract_json() -> String {
    flare_im_core_sdk_bindings_runtime::CLIENT_CONFIG_CONTRACT_JSON.to_string()
}
"""


def render_uniffi(doc: dict) -> str:
    return f"""// @generated by bindings/contract/tools/client_config_codegen.py
// Source: bindings/contract/client_config.json

/// Init/config contract JSON for mobile FFI planners.
pub fn client_config_contract_json() -> String {{
    flare_im_core_sdk_bindings_runtime::CLIENT_CONFIG_CONTRACT_JSON.to_string()
}}

pub fn client_init_request_example_json() -> String {{
    flare_im_core_sdk_bindings_runtime::CLIENT_INIT_REQUEST_EXAMPLE_JSON.to_string()
}}
"""


def render_c(doc: dict) -> str:
    example = json.dumps(
        doc.get("initRequest", {}).get("example", {}).get("sdk_config", {}),
        ensure_ascii=False,
        indent=2,
    )
    return f"""// @generated by bindings/contract/tools/client_config_codegen.py
// Source: bindings/contract/client_config.json
//! C `flare_sdk_init` accepts UTF-8 JSON matching [flare_im_core_sdk::client::SdkConfigOverlay].
//! Optional wrapper: `{{ "environment": "...", "sdk_config": {{ ... }} }}` via `flare_sdk_invoke_json("client.init", ...)`.

/// Example SdkConfigOverlay JSON (transport + protocol race).
pub const FLARE_SDK_CONFIG_EXAMPLE_JSON: &str = r#"{example}"#;
"""


def generate_all() -> dict[Path, str]:
    doc = load_doc()
    return {
        RUNTIME_OUT: render_runtime(doc),
        WASM_OUT: render_wasm(doc),
        UNIFFI_OUT: render_uniffi(doc),
        C_OUT: render_c(doc),
    }
