#!/usr/bin/env python3
"""Generate runtime direct invoke match from contract/direct_invoke.json."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

BINDINGS_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_DIR = BINDINGS_ROOT / "contract"
OUT = BINDINGS_ROOT / "shared" / "src" / "generated" / "direct_invoke.rs"
DIRECT_INVOKE_JSON = CONTRACT_DIR / "direct_invoke.json"


def render_route(entry: dict) -> str:
    route = entry["route"]
    body = entry["body"].strip()
    result = entry["result"]
    if result == "unit":
        tail = "Ok(BindingResponse::unit())"
    else:
        expr = entry.get("json_expr", "serde_json::to_value(())?")
        tail = f"dispatch_support::json({expr})"
    client_line = ""
    if not entry.get("skip_client"):
        client_line = "let client = session.client();\n            "
    body_block = f"{body}\n            " if body else ""
    arm = f"""
        "{route}" => {{
            {client_line}{body_block}{tail}
        }}"""
    cfg = entry.get("cfg")
    if not cfg and entry.get("dev_only", False):
        cfg = 'feature = "dev-test-token"'
    if cfg:
        return f"#[cfg({cfg})]{arm}"
    return arm


def render_module(routes: list[dict]) -> str:
    arms = "".join(render_route(r) for r in routes)
    route_lines: list[str] = []
    for route in routes:
        cfg = route.get("cfg")
        if not cfg and route.get("dev_only", False):
            cfg = 'feature = "dev-test-token"'
        if cfg:
            route_lines.append(f"#[cfg({cfg})]\n    \"{route['route']}\"")
        else:
            route_lines.append(f'"{route["route"]}"')
    routes_list = ",\n    ".join(route_lines)
    return f"""// @generated by bindings/contract/tools/direct_invoke_codegen.py
// Source: bindings/contract/direct_invoke.json

use serde_json::Value;

use crate::dispatch_support;
use crate::{{BindingResponse, InvokeSession}};
use flare_im_core_sdk::SdkState;
use flare_im_core_sdk::Result;

/// Routes handled outside JSON dispatch match tables.
pub const DIRECT_INVOKE_ROUTES: &[&str] = &[
    {routes_list},
];

pub fn is_direct_invoke_route(route: &str) -> bool {{
    DIRECT_INVOKE_ROUTES.contains(&route)
}}

fn sdk_state_json(state: SdkState) -> (&'static str, i32) {{
    use SdkState as S;
    match state {{
        S::Disconnected => ("disconnected", 0),
        S::Connecting => ("connecting", 1),
        S::Connected => ("connected", 2),
        S::Ready => ("ready", 3),
        S::Reconnecting => ("reconnecting", 4),
    }}
}}

pub async fn dispatch_direct(
    session: &impl InvokeSession,
    route: &str,
    request: &Value,
) -> Result<BindingResponse> {{
    match route {{{arms}
        _ => Err(crate::binding_operation_not_supported(route)),
    }}
}}
"""


def load_routes() -> list[dict[str, Any]]:
    if not DIRECT_INVOKE_JSON.exists():
        raise FileNotFoundError(
            f"{DIRECT_INVOKE_JSON} is missing; maintain routes in contract/direct_invoke.json"
        )
    with DIRECT_INVOKE_JSON.open("r", encoding="utf-8") as file:
        data = json.load(file)
    routes = data.get("routes")
    if not isinstance(routes, list):
        raise ValueError(f"{DIRECT_INVOKE_JSON} must contain a routes array")
    return routes


def generate_all() -> dict[Path, str]:
    return {OUT: render_module(load_routes())}


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"generated {path}")


if __name__ == "__main__":
    write_outputs(generate_all())
