#!/usr/bin/env python3
"""Generate platform event contract glue from contract/events.json."""

from __future__ import annotations

import json
from pathlib import Path

BINDINGS_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_DIR = BINDINGS_ROOT / "contract"
EVENTS_JSON = CONTRACT_DIR / "events.json"

TAURI_EVENT_EMIT = BINDINGS_ROOT / "tauri" / "src" / "generated" / "event_emit.rs"
WASM_EVENTS = BINDINGS_ROOT / "wasm" / "src" / "generated" / "events.rs"
UNIFFI_EVENTS = BINDINGS_ROOT / "uniffi" / "src" / "generated" / "events.rs"
RUNTIME_EVENT_REGISTRY = BINDINGS_ROOT / "shared" / "src" / "generated" / "event_registry.rs"
RUNTIME_EVENT_CODES = BINDINGS_ROOT / "shared" / "src" / "generated" / "event_codes.rs"


def read_events() -> dict:
    with EVENTS_JSON.open("r", encoding="utf-8") as file:
        return json.load(file)


def render_event_codes(events: list[dict], generator: str) -> str:
    lines = [
        f"// @generated by bindings/contract/tools/{generator}",
        "// Source: bindings/contract/events.json",
        "",
        "pub const FLARE_EVENT_UNKNOWN: i32 = 0;",
    ]
    for row in events:
        lines.append(f"pub const {row['cCodeName']}: i32 = {row['cCode']};")
    lines.append("")
    return "\n".join(lines)


def render_runtime_registry(events: list[dict]) -> str:
    rows = []
    for row in events:
        tauri = row.get("tauri")
        if not isinstance(tauri, str) or not tauri.startswith("im://"):
            continue
        rows.append(
            f"    ({row['cCode']}, {json.dumps(row['id'])}, {json.dumps(tauri)}),"
        )
    body = "\n".join(rows)
    return f"""// @generated by bindings/contract/tools/event_codegen.py
// Source: bindings/contract/events.json

/// Stable C event code → contract id → Tauri `im://*` name.
pub const EVENT_ROUTE_TABLE: &[(i32, &'static str, &'static str)] = &[
{body}
];

pub fn contract_event_id_for_code(code: i32) -> Option<&'static str> {{
    EVENT_ROUTE_TABLE
        .iter()
        .find(|(c, _, _)| *c == code)
        .map(|(_, id, _)| *id)
}}

pub fn tauri_event_name_for_code(code: i32) -> Option<&'static str> {{
    EVENT_ROUTE_TABLE
        .iter()
        .find(|(c, _, _)| *c == code)
        .map(|(_, _, name)| *name)
}}
"""


def render_tauri_emit() -> str:
    return """// @generated by bindings/contract/tools/event_codegen.py
// Source: bindings/contract/events.json — do not add events by hand in tauri/src.

use flare_im_core_sdk::event::SdkEvent;
use tauri::{AppHandle, Emitter};

use crate::convert::sdk_event_to_tauri;

/// Forward a core [`SdkEvent`] using contract `im://*` names.
pub fn emit_sdk_event<R: tauri::Runtime>(app: &AppHandle<R>, ev: &SdkEvent) -> bool {
    if let Some((name, payload)) = sdk_event_to_tauri(ev) {
        return app.emit(&name, payload).is_ok();
    }
    false
}
"""


def render_wasm_events(events: list[dict]) -> str:
    ids = [json.dumps(row["id"]) for row in events]
    tauri_rows = [
        (row["id"], row["tauri"])
        for row in events
        if isinstance(row.get("tauri"), str) and row["tauri"].startswith("im://")
    ]
    id_lines = ",\n    ".join(ids)
    route_lines = ",\n    ".join(
        f"({json.dumps(eid)}, {json.dumps(name)})" for eid, name in tauri_rows
    )
    return f"""// @generated by bindings/contract/tools/event_codegen.py
// Source: bindings/contract/events.json

/// Canonical contract event ids (parity with L3 SDK).
pub const CONTRACT_EVENT_IDS: &[&str] = &[
    {id_lines}
];

/// `(contract_event_id, web_event_name)` when a web adapter maps `im://*` names.
pub const WEB_EVENT_ROUTES: &[(&str, &str)] = &[
    {route_lines}
];
"""


def render_uniffi_events(events: list[dict]) -> str:
    codes = ",\n    ".join(
        f"({json.dumps(row['id'])}, {row['cCode']})" for row in events
    )
    return f"""// @generated by bindings/contract/tools/event_codegen.py
// Source: bindings/contract/events.json

/// Contract event id ↔ stable C ABI code.
pub const EVENT_CODE_TABLE: &[(&str, i32)] = &[
    {codes}
];
"""


def generate_all() -> dict[Path, str]:
    doc = read_events()
    events = doc.get("events", [])
    return {
        RUNTIME_EVENT_CODES: render_event_codes(events, "event_codegen.py"),
        RUNTIME_EVENT_REGISTRY: render_runtime_registry(events),
        TAURI_EVENT_EMIT: render_tauri_emit(),
        WASM_EVENTS: render_wasm_events(events),
        UNIFFI_EVENTS: render_uniffi_events(events),
    }
