#!/usr/bin/env python3
"""Generate platform glue: C json dispatch, Tauri handler, wasm exports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CONTRACT_DIR = ROOT / "contract"

C_JSON_DISPATCH = ROOT / "c" / "src" / "generated" / "json_dispatch.rs"
C_INVOKE = ROOT / "c" / "src" / "generated" / "invoke.rs"
TAURI_HANDLER = ROOT / "tauri" / "src" / "generated" / "handler.rs"
TAURI_INVOKE = ROOT / "tauri" / "src" / "generated" / "invoke.rs"
WASM_BINDINGS = ROOT / "wasm" / "src" / "generated" / "bindings.rs"
UNIFFI_INVOKE = ROOT / "uniffi" / "src" / "generated" / "invoke.rs"


def read_apis() -> dict[str, Any]:
    with (CONTRACT_DIR / "apis.json").open("r", encoding="utf-8") as f:
        return json.load(f)


def c_dispatch_channels(apis: dict[str, Any]) -> list[dict[str, str]]:
    """Unique C JSON dispatch entrypoints from contract."""
    seen: set[str] = set()
    rows: list[dict[str, str]] = []
    for module in apis.get("modules", []):
        for method in module.get("methods", []):
            c = method.get("c")
            values = c if isinstance(c, list) else [c]
            for item in values:
                if not isinstance(item, str) or ":" not in item:
                    continue
                symbol, _op = item.split(":", 1)
                if symbol in seen:
                    continue
                seen.add(symbol)
                channel = symbol.removeprefix("flare_").removesuffix("_json")
                runtime_group = (
                    "message_build"
                    if channel == "message_build"
                    else channel.replace("_dispatch", "")
                )
                rows.append(
                    {
                        "symbol": symbol,
                        "fn_name": symbol,
                        "channel": channel,
                        "runtime_group": runtime_group,
                    }
                )
    order = ["message_dispatch", "message_build", "conversation_dispatch", "media_dispatch"]
    rows.sort(key=lambda r: order.index(r["channel"]) if r["channel"] in order else 99)
    return rows


def tauri_lifecycle_commands(apis: dict[str, Any]) -> list[str]:
    """Commands that stay as dedicated Tauri IPC (AppHandle / non-JSON)."""
    keep = {
        "sdk_init",
        "sdk_login",
        "sdk_logout",
    }
    found: set[str] = set()
    for module in apis.get("modules", []):
        for method in module.get("methods", []):
            tauri = method.get("tauri")
            if isinstance(tauri, str) and tauri in keep:
                found.add(tauri)
    return sorted(found)


def render_c_json_dispatch(channels: list[dict[str, str]]) -> str:
    blocks: list[str] = []
    for ch in channels:
        if ch["channel"] == "message_build":
            blocks.append(
                f"""
/// C ABI: `{ch["symbol"]}`
#[unsafe(no_mangle)]
pub extern "C" fn {ch["fn_name"]}(
    handle: FlareHandle,
    request_json: *const c_char,
    context: *mut c_void,
    callback: FlareResultCallback,
) -> i32 {{
    message_build_dispatch_entry(handle, request_json, context, callback)
}}
"""
            )
            continue
        mod = ch["runtime_group"]
        check = f"flare_im_core_sdk_bindings_runtime::{mod}::is_{mod}_operation"
        dispatch = f"flare_im_core_sdk_bindings_runtime::{mod}::dispatch_{mod}"
        api = f"{mod}_api"
        extra = ", &inst.client" if mod == "capability" else ""
        call = f"{dispatch}(&api{extra}, &operation, params).await"
        blocks.append(
            f"""
/// C ABI: `{ch["symbol"]}`
#[unsafe(no_mangle)]
pub extern "C" fn {ch["fn_name"]}(
    handle: FlareHandle,
    op: *const c_char,
    params_json: *const c_char,
    context: *mut c_void,
    callback: FlareResultCallback,
) -> i32 {{
    json_dispatch_entry(handle, op, params_json, context, callback, |inst, operation, params| {{
        Box::pin(async move {{
            let api = inst.{api}().await?;
            if !{check}(&operation) {{
                return Err(flare_im_core_sdk_bindings_runtime::binding_operation_not_supported(&operation));
            }}
            {call}
        }})
    }})
}}
"""
        )
    return f"""// @generated by bindings/contract/tools/platform_codegen.py
#![allow(clippy::too_many_lines)]

use std::ffi::{{c_char, c_void}};

use crate::dispatch_common::{{json_dispatch_entry, message_build_dispatch_entry}};
use crate::types::{{FlareHandle, FlareResultCallback}};

{"".join(blocks)}
"""


def render_c_invoke() -> str:
    return """// @generated by bindings/contract/tools/platform_codegen.py

use std::ffi::{c_char, c_void};

use crate::dispatch_common::invoke_entry;
use crate::types::{FlareHandle, FlareResultCallback};

/// Universal contract invoke: `api_id` + JSON params (canonical ids from `contract/apis.json`).
#[unsafe(no_mangle)]
pub extern "C" fn flare_sdk_invoke_json(
    handle: FlareHandle,
    api_id: *const c_char,
    params_json: *const c_char,
    context: *mut c_void,
    callback: FlareResultCallback,
) -> i32 {
    invoke_entry(handle, api_id, params_json, context, callback)
}
"""


def render_tauri_handler(lifecycle: list[str]) -> str:
    lifecycle_paths = ",\n        ".join(
        f"crate::commands::lifecycle::{cmd}" for cmd in lifecycle
    )
    return f"""// @generated by bindings/contract/tools/platform_codegen.py
#![allow(dead_code)]

pub fn im_invoke_handler() -> impl Fn(tauri::ipc::Invoke) -> bool + Send + 'static {{
    tauri::generate_handler![
        crate::generated::invoke::sdk_invoke,
        {lifecycle_paths}
    ]
}}
"""


def render_tauri_invoke() -> str:
    return """// @generated by bindings/contract/tools/platform_codegen.py

use serde_json::Value;
use tauri::State;

use crate::state::SdkState;
use flare_im_core_sdk_bindings_runtime::{
    binding_response_to_value, invoke_api_id,
};

#[tauri::command]
pub async fn sdk_invoke(
    state: State<'_, SdkState>,
    api_id: String,
    request: Value,
) -> Result<Value, String> {
    invoke_api_id(&*state, &api_id, request)
        .await
        .map(binding_response_to_value)
        .map_err(|e| e.to_string())
}
"""


def render_wasm_bindings() -> str:
    return """// @generated by bindings/contract/tools/platform_codegen.py

use wasm_bindgen::prelude::*;

use flare_im_core_sdk_bindings_runtime::BINDING_CONTRACT_VERSION;

/// Contract version string for L2/L3 SDK parity checks.
#[wasm_bindgen(js_name = flareBindingContractVersion)]
pub fn flare_binding_contract_version() -> String {
    BINDING_CONTRACT_VERSION.to_string()
}

/// Canonical API invoke: `api_id` from `contract/apis.json` + JSON request body.
#[cfg(feature = "local-smoke-runtime")]
#[wasm_bindgen(js_name = flareInvoke)]
pub fn flare_invoke(
    runtime: &mut crate::smoke::FlareImWasmRuntime,
    api_id: &str,
    request_json: &str,
) -> Result<JsValue, JsValue> {
    runtime.invoke(api_id, request_json)
}
"""


def render_uniffi_invoke() -> str:
    return """// @generated by bindings/contract/tools/platform_codegen.py

/// UniFFI invoke placeholder — wire to `bindings_runtime::invoke_api_id` when session adapter exists.
pub fn invoke_contract_api(_api_id: &str, _request_json: &str) -> Result<String, String> {
    Err("UniFFI invoke adapter not implemented; use contract metadata only".to_string())
}
"""


def generate_all() -> dict[Path, str]:
    apis = read_apis()
    channels = c_dispatch_channels(apis)
    lifecycle = tauri_lifecycle_commands(apis)
    return {
        C_JSON_DISPATCH: render_c_json_dispatch(channels),
        C_INVOKE: render_c_invoke(),
        TAURI_HANDLER: render_tauri_handler(lifecycle),
        TAURI_INVOKE: render_tauri_invoke(),
        WASM_BINDINGS: render_wasm_bindings(),
        UNIFFI_INVOKE: render_uniffi_invoke(),
    }


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"generated {path}")
