use anyhow::{Context, Result, bail};
use serde_json::{Value, json};
use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
};

use crate::{
    arr, bool_field, core_contract_dir, core_root, include_path, include_paths, load_json,
    spec_dir, str_field, upsert_text_file,
};

const GENERATED_SHARED_CONTRACT_HINT: &str =
    "Generated by `cargo xtask sync-spec`; do not edit by hand.";

const PLATFORM_EVENT_GROUPS: &[(&str, &[&str])] = &[
    (
        "lifecycle",
        &[
            "initializing",
            "initialized",
            "init_failed",
            "login_succeeded",
            "login_failed",
            "logged_out",
            "disposed",
        ],
    ),
    ("connection", &["connecting", "reconnect_failed", "ready"]),
    (
        "message",
        &["burn_scheduled", "burned", "hard_deleted", "call_signal"],
    ),
    ("presence", &["changed"]),
    (
        "media",
        &["cache_changed", "upload_progress", "download_progress"],
    ),
    ("capability", &["changed", "unavailable"]),
];

const PLATFORM_ERROR_CODES: &[&str] = &[
    "notInitialized",
    "permissionDenied",
    "storageUnavailable",
    "operationCancelled",
    "capabilityUnavailable",
];

#[derive(Clone, Copy, Debug)]
struct CoreSchemaSpec {
    group: &'static str,
    file_name: &'static str,
    sdk_name: &'static str,
}

const CORE_SCHEMA_SPECS: &[CoreSchemaSpec] = &[
    CoreSchemaSpec {
        group: "conversations",
        file_name: "conversation_type.schema.json",
        sdk_name: "ConversationType",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "conversation_participant.schema.json",
        sdk_name: "ConversationParticipant",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "message_preview.schema.json",
        sdk_name: "MessagePreview",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "conversation.schema.json",
        sdk_name: "Conversation",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "timeline_sync_state.schema.json",
        sdk_name: "TimelineSyncState",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "bootstrap_home_timeline_request.schema.json",
        sdk_name: "BootstrapHomeTimelineRequest",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "open_conversation_timeline_request.schema.json",
        sdk_name: "OpenConversationTimelineRequest",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "home_timeline_snapshot.schema.json",
        sdk_name: "HomeTimelineSnapshot",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "conversation_timeline_snapshot.schema.json",
        sdk_name: "ConversationTimelineSnapshot",
    },
    CoreSchemaSpec {
        group: "conversations",
        file_name: "conversation_list_query.schema.json",
        sdk_name: "ConversationListQuery",
    },
    CoreSchemaSpec {
        group: "messages",
        file_name: "reaction_entry.schema.json",
        sdk_name: "ReactionEntry",
    },
    CoreSchemaSpec {
        group: "messages",
        file_name: "message_local_state.schema.json",
        sdk_name: "MessageLocalState",
    },
    CoreSchemaSpec {
        group: "messages",
        file_name: "message.schema.json",
        sdk_name: "Message",
    },
    CoreSchemaSpec {
        group: "messages",
        file_name: "message_search_kind.schema.json",
        sdk_name: "MessageSearchKind",
    },
    CoreSchemaSpec {
        group: "messages",
        file_name: "message_search_query.schema.json",
        sdk_name: "MessageSearchQuery",
    },
    CoreSchemaSpec {
        group: "sync",
        file_name: "conversation_version.schema.json",
        sdk_name: "ConversationVersion",
    },
    CoreSchemaSpec {
        group: "sync",
        file_name: "sync_conversation_summaries_request.schema.json",
        sdk_name: "SyncConversationSummariesRequest",
    },
    CoreSchemaSpec {
        group: "sync",
        file_name: "sync_conversation_summaries_response.schema.json",
        sdk_name: "SyncConversationSummariesResponse",
    },
    CoreSchemaSpec {
        group: "sync",
        file_name: "startup_home_sync_request.schema.json",
        sdk_name: "StartupHomeSyncRequest",
    },
    CoreSchemaSpec {
        group: "sync",
        file_name: "startup_home_sync_response.schema.json",
        sdk_name: "StartupHomeSyncResponse",
    },
];

#[derive(Clone, Debug)]
pub(crate) struct CoreAbiRef {
    pub(crate) api_id: String,
    pub(crate) symbol: String,
    pub(crate) dispatch_op: Option<String>,
}

#[derive(Clone, Debug)]
struct CoreContract {
    manifest: Value,
    apis: Value,
    direct_invoke: Value,
    dispatch: Value,
    c_typed_abi: Value,
    events: Value,
    errors: Value,
}

impl CoreContract {
    fn load(root: &Path) -> Result<Self> {
        let contract = core_contract_dir(root);
        Ok(Self {
            manifest: load_json(&contract.join("manifest.json"))?,
            apis: load_json(&contract.join("apis.json"))?,
            direct_invoke: load_json(&contract.join("direct_invoke.json"))?,
            dispatch: load_json(&contract.join("dispatch.json"))?,
            c_typed_abi: load_json(&contract.join("c_typed_abi.json"))?,
            events: load_json(&contract.join("events.json"))?,
            errors: load_json(&contract.join("errors.json"))?,
        })
    }

    fn verify_compatible_overlay(&self, overlay: &ClientSpecOverlay) -> Result<()> {
        let core_version = str_field(&self.manifest, "contractVersion");
        let overlay_version = str_field(&overlay.manifest, "ffiContractVersion");
        if !core_version.is_empty()
            && !overlay_version.is_empty()
            && core_version != overlay_version
        {
            bail!(
                "core contract version {core_version} does not match sdk-spec ffiContractVersion {overlay_version}"
            );
        }
        for (label, value, key) in [
            ("core apis", &self.apis, "modules"),
            ("core direct invoke", &self.direct_invoke, "routes"),
            ("core dispatch", &self.dispatch, "groups"),
            ("core typed C ABI", &self.c_typed_abi, "exports"),
            ("core events", &self.events, "events"),
        ] {
            if !value.get(key).is_some_and(Value::is_array) {
                bail!("{label} contract is missing `{key}` array");
            }
        }
        if !self
            .errors
            .get("cAbi")
            .and_then(|value| value.get("codes"))
            .is_some_and(Value::is_array)
        {
            bail!("core errors contract is missing `cAbi.codes` array");
        }
        self.verify_native_overlay(overlay)?;
        Ok(())
    }

    fn verify_native_overlay(&self, overlay: &ClientSpecOverlay) -> Result<()> {
        let Some(native) = overlay.include("native")? else {
            return Ok(());
        };
        let core_version = str_field(&self.manifest, "contractVersion");
        let native_contract = str_field(&native, "contract");
        if !core_version.is_empty()
            && !native_contract.is_empty()
            && core_version != native_contract
        {
            bail!(
                "core contract version {core_version} does not match native overlay contract {native_contract}"
            );
        }

        let local_operations = native_local_operation_ids(&native)?;
        let sdk_operations = overlay.operation_ids()?;
        for operation in &local_operations {
            if !sdk_operations.contains(operation) {
                bail!("native local operation `{operation}` is not declared by sdk-spec modules");
            }
        }

        let core_operations = self.operation_ids();
        if let Some(overrides) = native.get("operationOverrides") {
            let Some(overrides) = overrides.as_object() else {
                bail!("native operationOverrides must be an object");
            };
            for operation in overrides.keys() {
                if !core_operations.contains(operation) && !local_operations.contains(operation) {
                    bail!(
                        "native operation override `{operation}` is not backed by core contract and is not listed in native.localOperations"
                    );
                }
            }
        }
        Ok(())
    }

    fn operation_ids(&self) -> BTreeSet<String> {
        let mut operations = BTreeSet::new();
        for module in arr(self.apis.get("modules").unwrap_or(&Value::Null)) {
            for api in arr(module.get("apis").unwrap_or(&Value::Null)) {
                let id = str_field(api, "id");
                if !id.is_empty() {
                    operations.insert(id.to_string());
                }
            }
        }
        for route in arr(self.direct_invoke.get("routes").unwrap_or(&Value::Null)) {
            let id = str_field(route, "route");
            if !id.is_empty() {
                operations.insert(id.to_string());
            }
        }
        for export in arr(self.c_typed_abi.get("exports").unwrap_or(&Value::Null)) {
            let id = str_field(export, "api_id");
            if !id.is_empty() {
                operations.insert(id.to_string());
            }
        }
        for group in arr(self.dispatch.get("groups").unwrap_or(&Value::Null)) {
            let group_id = str_field(group, "id");
            if group_id.is_empty() {
                continue;
            }
            for operation in arr(group.get("operations").unwrap_or(&Value::Null)) {
                let op = str_field(operation, "op");
                if !op.is_empty() {
                    operations.insert(format!("{group_id}.{op}"));
                }
            }
        }
        operations
    }
}

#[derive(Clone, Debug)]
struct ClientSpecOverlay {
    manifest: Value,
    root: PathBuf,
}

impl ClientSpecOverlay {
    fn load(root: &Path) -> Result<Self> {
        let spec = spec_dir(root);
        Ok(Self {
            manifest: load_json(&spec.join("manifest.json"))?,
            root: spec,
        })
    }

    fn include(&self, key: &str) -> Result<Option<Value>> {
        include_path(&self.manifest, key)
            .map(|path| load_json(&self.root.join(path)))
            .transpose()
    }

    fn includes(&self, key: &str) -> Result<Vec<Value>> {
        include_paths(&self.manifest, key)
            .into_iter()
            .map(|path| load_json(&self.root.join(path)))
            .collect()
    }

    fn message_build_catalog(&self) -> Result<Option<Value>> {
        let path = self.root.join("shared/message_build_catalog.json");
        if path.is_file() {
            Ok(Some(load_json(&path)?))
        } else {
            Ok(None)
        }
    }

    fn operation_ids(&self) -> Result<BTreeSet<String>> {
        let mut operations = BTreeSet::new();
        for module in self.includes("modules")? {
            for method in arr(module.get("methods").unwrap_or(&Value::Null)) {
                let operation = str_field(method, "operation");
                if !operation.is_empty() {
                    operations.insert(operation.to_string());
                }
            }
        }
        Ok(operations)
    }
}

fn native_local_operation_ids(native: &Value) -> Result<BTreeSet<String>> {
    let mut operations = BTreeSet::new();
    let Some(local_operations) = native.get("localOperations") else {
        return Ok(operations);
    };
    if !local_operations.is_array() {
        bail!("native localOperations must be an array");
    }
    for entry in arr(local_operations) {
        let id = entry.as_str().unwrap_or_else(|| str_field(entry, "id"));
        if id.is_empty() {
            bail!("native localOperations entries must be strings or objects with `id`");
        }
        operations.insert(id.to_string());
    }
    Ok(operations)
}

#[derive(Clone, Debug)]
struct ExpandedClientSpec {
    value: Value,
}

impl ExpandedClientSpec {
    fn compose(root: &Path) -> Result<Self> {
        let core = CoreContract::load(root)?;
        let overlay = ClientSpecOverlay::load(root)?;
        core.verify_compatible_overlay(&overlay)?;
        let value = compose_expanded_client_spec(root, &core, &overlay)?;
        Ok(Self { value })
    }

    fn into_value(self) -> Value {
        self.value
    }
}

pub(crate) fn load_expanded_client_spec(root: &Path) -> Result<Value> {
    ExpandedClientSpec::compose(root).map(ExpandedClientSpec::into_value)
}

fn compose_expanded_client_spec(
    root: &Path,
    _core: &CoreContract,
    overlay: &ClientSpecOverlay,
) -> Result<Value> {
    let mut manifest = overlay.manifest.clone();
    for key in ["platforms", "errors", "states", "events", "listeners"] {
        if let Some(value) = overlay.include(key)? {
            merge_object(&mut manifest, value);
        }
    }
    if let Some(value) = overlay.include("native")? {
        manifest["native"] = value;
    } else {
        manifest["native"] = json!({});
    }
    let core_model_groups = core_schema_model_groups(root)?;
    let core_model_names = model_entry_names(&core_model_groups);
    let mut overlay_model_groups = overlay.includes("models")?;
    strip_core_schema_models_from_overlay(&mut overlay_model_groups, &core_model_names);
    let mut model_groups = core_model_groups;
    model_groups.extend(overlay_model_groups);
    manifest["modelGroups"] = Value::Array(model_groups);
    manifest["modules"] = Value::Array(overlay.includes("modules")?);
    if let Some(catalog) = overlay.message_build_catalog()? {
        manifest["messageBuildCatalog"] = catalog;
    }
    expand_message_builder_modules(root, &mut manifest)?;
    enrich_native_bindings(&mut manifest)?;
    Ok(manifest)
}

fn core_schema_model_groups(root: &Path) -> Result<Vec<Value>> {
    let schema_dir = core_contract_dir(root).join("generated/model_schemas");
    let mut by_group = BTreeMap::<String, (Vec<Value>, Vec<Value>)>::new();
    for spec in CORE_SCHEMA_SPECS {
        let schema = load_json(&schema_dir.join(spec.file_name))?;
        match core_schema_entry(spec, &schema)? {
            CoreSchemaEntry::Enum(value) => by_group
                .entry(spec.group.to_string())
                .or_default()
                .0
                .push(value),
            CoreSchemaEntry::Model(value) => by_group
                .entry(spec.group.to_string())
                .or_default()
                .1
                .push(value),
        }
    }
    Ok(by_group
        .into_iter()
        .map(|(group, (enums, models))| {
            json!({
                "group": group,
                "description": core_schema_group_description(&group),
                "source": "../flare-im-core-sdk/bindings/contract/generated/model_schemas",
                "enums": enums,
                "models": models,
            })
        })
        .collect())
}

enum CoreSchemaEntry {
    Enum(Value),
    Model(Value),
}

fn core_schema_entry(spec: &CoreSchemaSpec, schema: &Value) -> Result<CoreSchemaEntry> {
    if let Some(values) = schema_string_enum_values(schema) {
        return Ok(CoreSchemaEntry::Enum(json!({
            "name": spec.sdk_name,
            "description": schema_description(schema, spec.sdk_name),
            "values": values,
            "source": {
                "kind": "rust-json-schema",
                "file": spec.file_name,
                "rustType": str_field(schema, "xFlareRustType"),
            }
        })));
    }

    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        bail!(
            "core schema {} for {} must be a top-level object or enum",
            spec.file_name,
            spec.sdk_name
        );
    };
    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let mut fields = Vec::new();
    for (name, property) in properties {
        fields.push(json!({
            "name": name,
            "wireName": name,
            "type": sdk_type_from_schema(property)?,
            "required": core_schema_field_required(name, property, &required),
            "description": compact_doc_text(property.get("description").and_then(Value::as_str).unwrap_or("")),
        }));
    }
    if spec.sdk_name == "Message" {
        fields.push(json!({
            "name": "timelineKey",
            "wireName": "timelineKey",
            "type": "String",
            "required": true,
            "description": "Core-computed stable row key for timeline rendering.",
            "source": "IMMessage::serialize",
        }));
        fields.push(json!({
            "name": "timelineSortTs",
            "wireName": "timelineSortTs",
            "type": "UInt64",
            "required": true,
            "description": "Core-computed timeline sort timestamp in milliseconds.",
            "source": "IMMessage::serialize",
        }));
    }
    Ok(CoreSchemaEntry::Model(json!({
        "name": spec.sdk_name,
        "description": schema_description(schema, spec.sdk_name),
        "source": {
            "kind": "rust-json-schema",
            "file": spec.file_name,
            "rustType": str_field(schema, "xFlareRustType"),
        },
        "fields": fields,
    })))
}

fn schema_string_enum_values(schema: &Value) -> Option<Vec<Value>> {
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return Some(values.clone());
    }
    let one_of = schema
        .get("oneOf")
        .or_else(|| schema.get("anyOf"))
        .and_then(Value::as_array)?;
    let mut values = Vec::new();
    for item in one_of {
        if let Some(value) = item.get("const").and_then(Value::as_str) {
            values.push(Value::String(value.to_string()));
            continue;
        }
        if let Some(enum_values) = item.get("enum").and_then(Value::as_array) {
            values.extend(
                enum_values
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|value| Value::String(value.to_string())),
            );
        }
    }
    if values.is_empty() {
        None
    } else {
        Some(values)
    }
}

fn schema_description(schema: &Value, fallback_name: &str) -> String {
    compact_doc_text(
        schema
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or(fallback_name),
    )
}

fn compact_doc_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn core_schema_group_description(group: &str) -> &'static str {
    match group {
        "conversations" => "Core-owned conversation DTOs derived from Rust JsonSchema.",
        "messages" => "Core-owned message DTOs derived from Rust JsonSchema.",
        "sync" => "Core-owned sync DTOs derived from Rust JsonSchema.",
        "media" => "Core-owned media DTOs derived from Rust JsonSchema.",
        _ => "Core-owned DTOs derived from Rust JsonSchema.",
    }
}

fn core_schema_field_required(name: &str, property: &Value, required: &BTreeSet<&str>) -> bool {
    if schema_allows_null(property) {
        return false;
    }
    if name == "localState" && property.get("default").is_some() {
        return false;
    }
    // ⚠️ 此处**行为等价于恒真**，原式为 `required.contains(name) || true`。
    // clippy 把它标为 logic bug（`|| true` 让前半段成为死代码）。
    //
    // 保持原行为改写，因为它很可能是有意的：本函数处理的是 Rust `JsonSchema`
    // 派生出来的 schema，非 `Option` 字段序列化时必然存在，因此「非 nullable
    // 且不是带默认值的 localState」即必填，不依赖 schema 的 `required` 列表
    // （该列表对 Rust 派生类型并不完整）。
    //
    // 若本意其实是 `required.contains(name)`，改动会让一批字段从必填变可选，
    // 进而改变生成的 TS 类型 —— 属于需要人工确认的语义变更，不在此擅自更改。
    let _ = required;
    true
}

fn sdk_type_from_schema(schema: &Value) -> Result<String> {
    let normalized = non_null_schema(schema);
    if let Some(reference) = normalized.get("$ref").and_then(Value::as_str) {
        return Ok(sdk_type_name_from_ref(reference));
    }
    if let Some(any_of) = normalized
        .get("anyOf")
        .or_else(|| normalized.get("oneOf"))
        .and_then(Value::as_array)
        && let Some(non_null) = any_of.iter().find(|item| !schema_is_null(item))
    {
        return sdk_type_from_schema(non_null);
    }
    match normalized.get("type") {
        Some(Value::String(kind)) => sdk_type_from_schema_type(kind, normalized),
        Some(Value::Array(kinds)) => {
            let Some(kind) = kinds
                .iter()
                .filter_map(Value::as_str)
                .find(|kind| *kind != "null")
            else {
                return Ok("JsonObject".to_string());
            };
            sdk_type_from_schema_type(kind, normalized)
        }
        // 无 type 字段时一律退到 JsonObject —— 原本按 properties 是否存在分了两支，
        // 但两支返回值相同，判断没有作用。
        _ => Ok("JsonObject".to_string()),
    }
}

fn sdk_type_from_schema_type(kind: &str, schema: &Value) -> Result<String> {
    Ok(match kind {
        "string" => "String".to_string(),
        "boolean" => "Boolean".to_string(),
        "integer" => integer_schema_type(schema),
        "number" => "JsonObject".to_string(),
        "object" => object_schema_type(schema)?,
        "array" => array_schema_type(schema)?,
        _ => "JsonObject".to_string(),
    })
}

fn integer_schema_type(schema: &Value) -> String {
    match schema.get("format").and_then(Value::as_str) {
        Some("int32") => "Int32".to_string(),
        Some("uint32") => "UInt32".to_string(),
        Some("uint64") => "UInt64".to_string(),
        Some("int64") => "Int64".to_string(),
        Some("uint8") => "UInt32".to_string(),
        _ => "Int64".to_string(),
    }
}

fn object_schema_type(schema: &Value) -> Result<String> {
    let Some(additional) = schema.get("additionalProperties") else {
        return Ok("JsonObject".to_string());
    };
    if additional.get("type").and_then(Value::as_str) == Some("string") {
        return Ok("StringMap".to_string());
    }
    if additional.get("type").and_then(Value::as_str) == Some("array")
        && additional
            .get("items")
            .and_then(|items| items.get("format"))
            .and_then(Value::as_str)
            == Some("uint8")
    {
        return Ok("BinaryMap".to_string());
    }
    Ok("JsonObject".to_string())
}

fn array_schema_type(schema: &Value) -> Result<String> {
    let Some(items) = schema.get("items") else {
        return Ok("JsonObject".to_string());
    };
    if items.get("format").and_then(Value::as_str) == Some("uint8") {
        return Ok("JsonObject".to_string());
    }
    Ok(format!("{}List", sdk_type_from_schema(items)?))
}

fn non_null_schema(schema: &Value) -> &Value {
    if let Some(any_of) = schema
        .get("anyOf")
        .or_else(|| schema.get("oneOf"))
        .and_then(Value::as_array)
        && let Some(non_null) = any_of.iter().find(|item| !schema_is_null(item))
    {
        return non_null;
    }
    schema
}

fn schema_allows_null(schema: &Value) -> bool {
    match schema.get("type") {
        Some(Value::String(kind)) if kind == "null" => true,
        Some(Value::Array(kinds)) => kinds
            .iter()
            .filter_map(Value::as_str)
            .any(|kind| kind == "null"),
        _ => schema
            .get("anyOf")
            .or_else(|| schema.get("oneOf"))
            .and_then(Value::as_array)
            .is_some_and(|items| items.iter().any(schema_is_null)),
    }
}

fn schema_is_null(schema: &Value) -> bool {
    matches!(schema.get("type").and_then(Value::as_str), Some("null"))
}

fn sdk_type_name_from_ref(reference: &str) -> String {
    let raw = reference.rsplit('/').next().unwrap_or(reference);
    match raw {
        "Elem" => "MessageContent",
        "IMMessage" => "Message",
        "MessagePreviewElem" => "MessagePreview",
        "SdkConversationType" => "ConversationType",
        other => other,
    }
    .to_string()
}

fn model_entry_names(groups: &[Value]) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for group in groups {
        for key in ["enums", "models"] {
            for entry in arr(group.get(key).unwrap_or(&Value::Null)) {
                let name = str_field(entry, "name");
                if !name.is_empty() {
                    names.insert(name.to_string());
                }
            }
        }
    }
    names
}

fn strip_core_schema_models_from_overlay(groups: &mut Vec<Value>, core_names: &BTreeSet<String>) {
    for group in groups.iter_mut() {
        for key in ["enums", "models"] {
            if let Some(items) = group.get_mut(key).and_then(Value::as_array_mut) {
                items.retain(|entry| !core_names.contains(str_field(entry, "name")));
            }
        }
    }
    groups.retain(|group| {
        !arr(group.get("enums").unwrap_or(&Value::Null)).is_empty()
            || !arr(group.get("models").unwrap_or(&Value::Null)).is_empty()
    });
}

fn enrich_native_bindings(spec: &mut Value) -> Result<()> {
    let native = spec.get("native").cloned().unwrap_or_else(|| json!({}));
    let Some(modules) = spec.get_mut("modules").and_then(Value::as_array_mut) else {
        return Ok(());
    };
    for module in modules {
        let Some(methods) = module.get_mut("methods").and_then(Value::as_array_mut) else {
            continue;
        };
        for method in methods {
            let binding = native_binding_for(&native, method)?;
            if let Some(object) = method.as_object_mut() {
                object.insert("nativeBinding".to_string(), binding);
            }
        }
    }
    Ok(())
}

fn native_binding_for(native: &Value, method: &Value) -> Result<Value> {
    let defaults = native.get("defaults").unwrap_or(&Value::Null);
    let response = str_field(method, "response");
    let transport = str_field(method, "transport");
    let operation = str_field(method, "operation");
    if operation.is_empty() {
        bail!("sdk-spec method is missing operation");
    }

    let response_encoding = defaults
        .get("responseEncodingByResponse")
        .and_then(|value| value.get(response))
        .and_then(Value::as_str)
        .unwrap_or("json-object");
    let request_encoding = defaults
        .get("requestEncodingByTransport")
        .and_then(|value| value.get(transport))
        .and_then(Value::as_str)
        .unwrap_or("typed-ffi");
    let mut return_mode = if transport == "catalog-static" {
        "local"
    } else {
        "callback"
    };
    if response_encoding == "unit"
        && matches!(
            transport,
            "dispatch-json" | "message-dispatch-json" | "capability-dispatch-json"
        )
    {
        return_mode = "callback-unit";
    }

    let mut binding = json!({
        "requestEncoding": request_encoding,
        "responseEncoding": response_encoding,
        "returnMode": return_mode,
        "callback": defaults.get("callback").cloned().unwrap_or(Value::Null),
        "asyncReturn": defaults.get("asyncReturn").cloned().unwrap_or(Value::Null),
        "handlePolicy": defaults
            .get("handlePolicy")
            .and_then(Value::as_str)
            .unwrap_or("client-handle"),
    });
    if let Some(override_value) = native
        .get("operationOverrides")
        .and_then(|value| value.get(operation))
    {
        merge_object(&mut binding, override_value.clone());
    }
    Ok(binding)
}

fn merge_object(target: &mut Value, source: Value) {
    if let (Some(target), Some(source)) = (target.as_object_mut(), source.as_object()) {
        for (key, value) in source {
            target.insert(key.clone(), value.clone());
        }
    }
}

fn expand_message_builder_modules(root: &Path, spec: &mut Value) -> Result<()> {
    let default_catalog_entries = spec
        .get("messageBuildCatalog")
        .and_then(|catalog| catalog.get("entries"))
        .cloned()
        .unwrap_or_else(|| json!([]));
    let Some(modules) = spec.get_mut("modules").and_then(Value::as_array_mut) else {
        return Ok(());
    };
    for module in modules {
        if !bool_field(module, "generateBuildMethodsFromCatalog") {
            continue;
        }
        let entries = if let Some(catalog_ref) = module.get("catalog").and_then(Value::as_str) {
            load_json(&spec_dir(root).join(catalog_ref))?["entries"].clone()
        } else {
            default_catalog_entries.clone()
        };
        let build_c_api = module
            .get("buildDispatch")
            .and_then(|dispatch| dispatch.get("cApi"))
            .and_then(Value::as_str)
            .unwrap_or("flare_message_build_json");
        let generated = arr(&entries)
            .iter()
            .map(|entry| {
                json!({
                    "name": str_field(entry, "method"),
                    "operation": format!("message_builder.{}", str_field(entry, "op")),
                    "transport": "dispatch-json",
                    "cApi": build_c_api,
                    "dispatchOp": str_field(entry, "op"),
                    "request": str_field(entry, "request"),
                    "response": "Message",
                    "stability": entry.get("stability").and_then(Value::as_str).unwrap_or("stable"),
                    "description": entry.get("summary").and_then(Value::as_str).unwrap_or(""),
                })
            })
            .collect::<Vec<_>>();
        let methods = module
            .get_mut("methods")
            .and_then(Value::as_array_mut)
            .context("message_builder module has no methods array")?;
        methods.extend(generated);
    }
    Ok(())
}

pub(crate) fn sync_shared_contracts(root: &Path, check: bool) -> Result<()> {
    let mut drifted = Vec::new();
    sync_message_build_catalog(root, check, &mut drifted)?;
    sync_shared_events(root, check, &mut drifted)?;
    sync_shared_errors(root, check, &mut drifted)?;
    if !drifted.is_empty() {
        let details = drifted.join("\n  - ");
        bail!("sdk-spec shared generated contracts drifted:\n  - {details}");
    }
    if !check {
        println!("sdk-spec shared generated contracts synced");
    }
    Ok(())
}

fn sync_message_build_catalog(root: &Path, check: bool, drifted: &mut Vec<String>) -> Result<()> {
    let core_apis_path = core_root(root).join("bindings/contract/apis.json");
    let catalog_path = spec_dir(root).join("shared/message_build_catalog.json");
    if !core_apis_path.is_file() {
        bail!("missing L1 contract: {}", core_apis_path.display());
    }
    let core_apis = load_json(&core_apis_path)?;
    let existing_catalog = if catalog_path.is_file() {
        load_json(&catalog_path)?
    } else {
        json!({})
    };
    let by_op = arr(existing_catalog.get("entries").unwrap_or(&Value::Null))
        .iter()
        .map(|entry| (str_field(entry, "op").to_string(), entry.clone()))
        .collect::<BTreeMap<_, _>>();
    let mut l1_ops = BTreeMap::<String, String>::new();
    for module in arr(core_apis
        .get("modules")
        .unwrap_or(core_apis.get("groups").unwrap_or(&Value::Null)))
    {
        if str_field(module, "id") != "message_builder" {
            continue;
        }
        for method in arr(module.get("methods").unwrap_or(&Value::Null)) {
            if let Some(op) = op_from_l1(method) {
                l1_ops
                    .entry(op)
                    .or_insert_with(|| str_field(method, "id").to_string());
            }
        }
    }
    let entries = l1_ops
        .iter()
        .map(|(op, source_operation)| build_catalog_entry(op, source_operation, by_op.get(op)))
        .collect::<Result<Vec<_>>>()?;
    let payload = json!({
        "description": existing_catalog
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or("Canonical message build operations aligned with flare-im-core-sdk MessageBuildApi."),
        "source": "../flare-im-core-sdk/bindings/contract/apis.json#message_builder",
        "entries": entries,
    });
    upsert_json_pretty(&catalog_path, &payload, check, drifted)?;
    if !check {
        println!("updated {} ({} ops)", catalog_path.display(), l1_ops.len());
    }
    Ok(())
}

fn sync_shared_events(root: &Path, check: bool, drifted: &mut Vec<String>) -> Result<()> {
    let core_events_path = core_root(root).join("bindings/contract/events.json");
    let events_path = spec_dir(root).join("shared/events.json");
    let core_events = load_json(&core_events_path)?;
    let mut groups = BTreeMap::<String, Vec<String>>::new();

    for (group, names) in PLATFORM_EVENT_GROUPS {
        groups
            .entry((*group).to_string())
            .or_default()
            .extend(names.iter().map(|name| (*name).to_string()));
    }

    for event in arr(core_events.get("events").unwrap_or(&Value::Null)) {
        let id = str_field(event, "id");
        let Some((group, name)) = id.split_once('.') else {
            bail!("core event id must be kind.name: {id}");
        };
        let names = groups.entry(group.to_string()).or_default();
        if !names.iter().any(|existing| existing == name) {
            names.push(name.to_string());
        }
    }

    let events = groups
        .into_iter()
        .map(|(event_type, names)| {
            json!({
                "type": event_type,
                "names": names,
            })
        })
        .collect::<Vec<_>>();
    let payload = json!({
        "generated": true,
        "description": GENERATED_SHARED_CONTRACT_HINT,
        "source": "../flare-im-core-sdk/bindings/contract/events.json",
        "events": events,
    });
    upsert_json_pretty(&events_path, &payload, check, drifted)
}

fn sync_shared_errors(root: &Path, check: bool, drifted: &mut Vec<String>) -> Result<()> {
    let core_errors_path = core_root(root).join("bindings/contract/errors.json");
    let errors_path = spec_dir(root).join("shared/errors.json");
    let core_errors = load_json(&core_errors_path)?;
    let existing = if errors_path.is_file() {
        load_json(&errors_path)?
    } else {
        json!({})
    };
    let mut error_codes = PLATFORM_ERROR_CODES
        .iter()
        .map(|code| (*code).to_string())
        .collect::<BTreeSet<_>>();
    for code in arr(core_errors
        .get("cAbi")
        .and_then(|cabi| cabi.get("codes"))
        .unwrap_or(&Value::Null))
    {
        let Some(client_code) = c_abi_error_name_to_client_code(str_field(code, "name")) else {
            continue;
        };
        error_codes.insert(client_code.to_string());
    }
    let payload = json!({
        "generated": true,
        "description": GENERATED_SHARED_CONTRACT_HINT,
        "source": "../flare-im-core-sdk/bindings/contract/errors.json",
        "errorShape": existing.get("errorShape").cloned().unwrap_or_else(default_error_shape),
        "errorCodes": error_codes.into_iter().collect::<Vec<_>>(),
        "cAbi": core_errors.get("cAbi").cloned().unwrap_or_else(|| json!({})),
        "platformMapping": existing
            .get("platformMapping")
            .filter(|value| value.as_object().is_some_and(|object| !object.is_empty()))
            .cloned()
            .unwrap_or_else(default_platform_mapping),
    });
    upsert_json_pretty(&errors_path, &payload, check, drifted)
}

fn c_abi_error_name_to_client_code(name: &str) -> Option<&'static str> {
    Some(match name {
        "FLARE_OK" => return None,
        "FLARE_ERR_INVALID_HANDLE" => "invalidHandle",
        "FLARE_ERR_INVALID_PARAM" => "invalidParameter",
        "FLARE_ERR_NOT_CONNECTED" => "notConnected",
        "FLARE_ERR_OPERATION_TIMEOUT" => "timeout",
        "FLARE_ERR_NETWORK_ERROR" => "networkUnavailable",
        "FLARE_ERR_AUTH_FAILED" => "unauthorized",
        "FLARE_ERR_TOKEN_EXPIRED" => "tokenExpired",
        "FLARE_ERR_INTERNAL" => "internal",
        "FLARE_ERR_JSON_PARSE" => "jsonParse",
        "FLARE_ERR_NULL_POINTER" => "nullPointer",
        "FLARE_ERR_FFI_PANIC" => "ffiPanic",
        _ => "internal",
    })
}

fn default_error_shape() -> Value {
    json!({
        "name": "FlareSdkError",
        "fields": [
            { "name": "code", "type": "SdkErrorCode", "required": true },
            { "name": "message", "type": "string", "required": true },
            { "name": "operation", "type": "string", "required": false },
            { "name": "retryable", "type": "boolean", "required": false },
            { "name": "details", "type": "object", "required": false },
            { "name": "cause", "type": "platform-native-error", "required": false }
        ]
    })
}

fn default_platform_mapping() -> Value {
    json!({
        "typescript": {
            "base": "FlareSdkError",
            "typed": "SdkErrorCode union from generated errorCodes",
        },
        "kotlin": {
            "base": "FlareSdkException",
            "typed": "sealed subclasses by cAbi.codes.name",
        },
        "swift": {
            "base": "FlareSdkError",
            "typed": "enum cases by cAbi.codes.name",
        },
        "dart": {
            "base": "FlareSdkException",
            "typed": "factory by cAbi.codes.name",
        },
    })
}

fn upsert_json_pretty(
    path: &Path,
    value: &Value,
    check: bool,
    drifted: &mut Vec<String>,
) -> Result<()> {
    let body = serde_json::to_string_pretty(value)?;
    upsert_text_file(path, &format!("{body}\n"), check, drifted)
}

fn op_from_l1(method: &Value) -> Option<String> {
    match method.get("c") {
        Some(Value::Array(items)) => items
            .iter()
            .filter_map(Value::as_str)
            .find_map(op_from_c_ref),
        Some(Value::String(raw)) => op_from_c_ref(raw),
        _ => None,
    }
}

fn op_from_c_ref(raw: &str) -> Option<String> {
    raw.find(":create_")
        .map(|index| raw[index + 1..].to_string())
}

fn build_catalog_entry(
    op: &str,
    source_operation: &str,
    existing: Option<&Value>,
) -> Result<Value> {
    if let Some(existing) = existing {
        return Ok(json!({
            "op": op,
            "method": method_by_op(op)?,
            "request": request_by_op(op)?,
            "contentType": content_type_by_op(op)?,
            "messageType": message_type_by_op(op)?,
            "summary": existing
                .get("summary")
                .and_then(Value::as_str)
                .unwrap_or("Build message"),
            "stability": existing
                .get("stability")
                .and_then(Value::as_str)
                .unwrap_or("stable"),
            "sourceOperation": source_operation,
        }));
    }
    Ok(json!({
        "op": op,
        "method": method_by_op(op)?,
        "request": request_by_op(op)?,
        "contentType": content_type_by_op(op)?,
        "messageType": message_type_by_op(op)?,
        "summary": format!("Build {} message", op.trim_start_matches("create_").replace('_', " ")),
        "stability": "stable",
        "sourceOperation": source_operation,
    }))
}

fn method_by_op(op: &str) -> Result<&'static str> {
    Ok(match op {
        "create_text" => "buildText",
        "create_quote" => "buildQuote",
        "create_thread_reply" => "buildThreadReply",
        "create_forward" => "buildForward",
        "create_image" => "buildImage",
        "create_image_group" => "buildImageGroup",
        "create_video" => "buildVideo",
        "create_audio" => "buildAudio",
        "create_file" => "buildFile",
        "create_emoji" => "buildEmoji",
        "create_location" => "buildLocation",
        "create_sticker" => "buildSticker",
        "create_link_card" => "buildLinkCard",
        "create_card" => "buildCard",
        "create_mini_program" => "buildMiniProgram",
        "create_rich_doc" => "buildRichDoc",
        "create_system" => "buildSystem",
        "create_notification" => "buildNotification",
        "create_vote" => "buildVote",
        "create_task" => "buildTask",
        "create_schedule" => "buildSchedule",
        "create_announcement" => "buildAnnouncement",
        "create_custom" => "buildCustom",
        "create_placeholder" => "buildPlaceholder",
        "create_with_content" => "buildWithContent",
        _ => bail!("unknown message build op: {op}"),
    })
}

fn request_by_op(op: &str) -> Result<&'static str> {
    Ok(match op {
        "create_text" => "BuildTextMessageRequest",
        "create_quote" => "BuildQuoteMessageRequest",
        "create_thread_reply" => "BuildThreadReplyMessageRequest",
        "create_forward" => "BuildForwardMessageRequest",
        "create_image" => "BuildImageMessageRequest",
        "create_image_group" => "BuildImageGroupMessageRequest",
        "create_video" => "BuildVideoMessageRequest",
        "create_audio" => "BuildAudioMessageRequest",
        "create_file" => "BuildFileMessageRequest",
        "create_emoji" => "BuildEmojiMessageRequest",
        "create_location" => "BuildLocationMessageRequest",
        "create_sticker" => "BuildStickerMessageRequest",
        "create_link_card" => "BuildLinkCardMessageRequest",
        "create_card" => "BuildCardMessageRequest",
        "create_mini_program" => "BuildMiniProgramMessageRequest",
        "create_rich_doc" => "BuildRichDocMessageRequest",
        "create_system" => "BuildSystemMessageRequest",
        "create_notification" => "BuildNotificationMessageRequest",
        "create_vote" => "BuildVoteMessageRequest",
        "create_task" => "BuildTaskMessageRequest",
        "create_schedule" => "BuildScheduleMessageRequest",
        "create_announcement" => "BuildAnnouncementMessageRequest",
        "create_custom" => "BuildCustomMessageRequest",
        "create_placeholder" => "BuildPlaceholderMessageRequest",
        "create_with_content" => "BuildWithContentMessageRequest",
        _ => bail!("unknown message build op: {op}"),
    })
}

fn content_type_by_op(op: &str) -> Result<&'static str> {
    Ok(match op {
        "create_text" => "text",
        "create_quote" => "quote",
        "create_thread_reply" => "text",
        "create_forward" => "forward",
        "create_image" => "image",
        "create_image_group" => "image_group",
        "create_video" => "video",
        "create_audio" => "audio",
        "create_file" => "file",
        "create_emoji" => "emoji",
        "create_location" => "location",
        "create_sticker" => "sticker",
        "create_link_card" => "link_card",
        "create_card" => "card",
        "create_mini_program" => "mini_program",
        "create_rich_doc" => "rich_text",
        "create_system" => "system",
        "create_notification" => "notification",
        "create_vote" => "vote",
        "create_task" => "task",
        "create_schedule" => "schedule",
        "create_announcement" => "announcement",
        "create_custom" | "create_with_content" => "custom",
        "create_placeholder" => "placeholder",
        _ => bail!("unknown message build op: {op}"),
    })
}

fn message_type_by_op(op: &str) -> Result<i64> {
    Ok(match op {
        "create_text" => 1,
        "create_image" => 2,
        "create_video" => 3,
        "create_audio" => 4,
        "create_file" => 5,
        "create_location" => 6,
        "create_card" => 7,
        "create_sticker" => 8,
        "create_emoji" => 9,
        "create_link_card" => 11,
        "create_forward" => 12,
        "create_mini_program" => 13,
        "create_thread_reply" => 1,
        "create_quote" => 15,
        "create_rich_doc" => 30,
        "create_image_group" => 32,
        "create_system" => 60,
        "create_notification" => 61,
        "create_vote" => 80,
        "create_task" => 81,
        "create_schedule" => 82,
        "create_announcement" => 83,
        "create_custom" | "create_with_content" => 100,
        "create_placeholder" => 111,
        _ => bail!("unknown message build op: {op}"),
    })
}
