[package]
name = "flare-im-core-sdk-wasm"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Flare IM Core SDK WebAssembly binding"

[lib]
name = "flare_im_core_sdk_wasm"
crate-type = ["cdylib", "rlib"]

[features]
default = ["production-runtime"]
dev-test-token = [
    "flare-im-core-sdk/dev-test-token",
    "flare-im-core-sdk-bindings-runtime/dev-test-token",
]
local-smoke-runtime = []
production-runtime = []

[dependencies]
console_error_panic_hook = "0.1"
async-trait = "0.1"
flare-core = { workspace = true, default-features = false, features = ["wasm"] }
flare-im-core-sdk-bindings-runtime = { path = "../shared" }
flare-im-core-sdk-storage-indexeddb = { path = "../../storage/indexeddb" }
flare-im-core-sdk = { path = "../.." }
flare-proto = { workspace = true }
js-sys = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
tracing = "0.1"
futures-channel = "0.3"
tokio = { version = "1", default-features = false, features = ["sync", "macros", "rt", "time"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
